### ISSUE TITLE
ROS release

### ISSUE THREAD

**Issue by achim-k** [LOEWE-emergenCITY/ros2_babel_fish#7]
Are you planning to release this package (ideally from `humble` onwards)? We are planning to use it for [foxglove_bridge](https://github.com/foxglove/ros-foxglove-bridge).

**Comment by StefanFabian** [comment]
That's cool!
Currently I'm planning to release it from Jazzy onwards because my backport PR (ros2/rosidl_typesupport#149) that fixes the introspection for services and actions was not merged for humble yet.

**Comment by matthews-jca** [comment]
With the upstream backport complete on the humble side, what efforts would be required to support humble long term?

**Comment by StefanFabian** [comment]
None to my knowledge. I have already released it for humble. If it's not available yet, it should be after the next sync.

**Comment by StefanFabian** [comment]
Released for all current LTS versions.
